services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    command: >
      sh -c "npm run prod:main"
    ports:
      - ${PORT}:${PORT}
    environment:
      - MAX_SESSIONS_PER_USER=5
      - CACHE_TTL=10
      - SWAGGER_USER=${SWAGGER_USER}
      - SWAGGER_PASSWORD=${SWAGGER_PASSWORD}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT=${PORT}

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    command: >
      sh -c "npm run prod:admin"
    ports:
      - ${PORT_ADMIN}:${PORT_ADMIN}
    environment:
      - CACHE_TTL=10
      - SWAGGER_USER=${SWAGGER_USER}
      - SWAGGER_PASSWORD=${SWAGGER_PASSWORD}
      - MAX_SESSIONS_PER_USER=5
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT_ADMIN=${PORT_ADMIN}

networks:
  default:
    driver: bridge
