# WARNING: This file is DEV version.

version: '3.8'

services:
  main:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.main
    command: >
      sh -c "npm run reset && npm run prod:main"
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/template
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT=3000

  admin:
    depends_on:
      postgres:
        condition: service_healthy
      main:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.admin
    command: >
      sh -c "npm run reset && npm run prod:admin"
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/template
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - PORT_ADMIN=3001

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'template']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
