version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npx prisma migrate reset --force && npm run start:prod"
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - ACCESS_SECRET=access_secret
      - REFRESH_SECRET=refresh_secret
      - PORT=3000
    depends_on:
      - db

volumes:
  db_data:
